name: "Twilio-Whatsapp Action"
description: "Recieve repo notifications on your whatsapp when a push occurs in the master branch"
author: "mdb571"
branding:
  icon: message-square
  color: black

inputs:
  from:
    description: "The twilio whatsapp number from which the sms should be sent"
    required: true
  to:
    description: "The number which is configured with twilio"
    required: true
  twilio_account_sid:
    description: "Twilio Accout SID from twilio console"
    required: true
  twilio_auth:
    description: "Twilio Authentication token from console"
    required: true
  iutitle: 
    description: 'Issue Title'
    default: ${{ github.event.issue.title }}
  iunum:
    description: 'Issue Number'
    default: ${{ github.event.issue.number }}
  iu_actor: 
    description: 'Issue Triggerer'
    default: ${{ github.event.issue.user.login }}
  iu_body:
    description: 'Issue Body'
    default: ${{ github.event.issue.body }}
  iu_com:
    description: 'Issue Comment'
    default: ${{github.event.comment.body}}
  event_action:
    description: "Current state of the issue/pull request"
    default: ${{ github.event.action }}
  prnum:
    description: 'PR Number'
    default: ${{ github.event.pull_request.number }}
  prtitle:
    description: 'PR Title'
    default: ${{ github.event.pull_request.title }}
  pr_body:
    description: 'PR Content'
    default: ${{ github.event.pull_request.body }}
  stargazers:
    description: 'Stars of the Repo'
    default: ${{ github.event.repository.stargazers_count }}
  forkers:
    description: 'Number of Forks'
    default: ${{ github.event.repository.forks_count }}

runs:
  using: "docker"
  image: "Dockerfile"